name: Deploy and Notify

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy
      run: |
        # Placeholder deployment script
        echo "Deploying the application..."
        # Add your deployment logic, and handle success or failure

    - name: Set Deployment Status - Success
      if: success()
      run: |
        # Placeholder for setting deployment status for success
        echo "Setting deployment status - Success"

    - name: Set Deployment Status - Failure
      if: failure()
      run: |
        # Placeholder for setting deployment status for failure
        echo "Setting deployment status - Failure"

  notify:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Send Email Notification - Success
      if: success()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: 123rajubhovi@gmail.com
        password: Raju@123
        subject: "Deployment Status - Success"
        to: rajubhovi999@gmail.com
        from: 123rajubhovi@gmail.com
        body: "The deployment was successful."

    - name: Send Email Notification - Failure
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.example.com
        server_port: 587
        username: 123rajubhovi@gmail.com
        password: Raju@123
        subject: "Deployment Status - Failure"
        to: rajubhovi999@gmail.com
        from: 123rajubhovi@gmail.com
        body: "The deployment failed. Please check the logs for details."
