name: Java App Service CI/CD

on:
  pull_request:
    types: [closed]
    branches: [develop, dev/**, uat]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
